### ISSUE TITLE
Bower.json main definition

### ISSUE THREAD

**Issue by vogloblinsky** [antoinechalifour/angular-webrtc#1]
Please fix your bower.json "main" definition from "gruntfile.js" to "dist/angular-webrtc.js"

It breaks tools like wiredep.

Thanks

**Comment by antoinechalifour** [comment]
Done. Hopefully everything is ok now.

However I'm not quite sure where this project is going, I'm not actively maintaining / developing it.

**Comment by vogloblinsky** [comment]
Ok thanks.
